#include "BSP_Clock.h"

extern RTC_HandleTypeDef RtcHandle;

void clock_init( void ) {
    //  initialized by EW
}

void clock_getDateTime( ApplicationDateTime pDT ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    pDT->Month = sDate.Month;
    pDT->WeekDay = sDate.WeekDay;
    pDT->Date = sDate.Date;

    pDT->Hour = sTime.Hours;
    pDT->Minute = sTime.Minutes;
    pDT->Second = sTime.Seconds;
}

void clock_setDateTime( ApplicationDateTime pDT ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    sDate.Date = pDT->Date;
    sDate.Month = pDT->Month;
    sDate.WeekDay = pDT->WeekDay;

    sTime.Hours = pDT->Hour;
    sTime.Minutes = pDT->Minute;
    sTime.Seconds = pDT->Second;

    HAL_RTC_SetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
    HAL_RTC_SetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
}

/*****************************************************************************/
//  Set individual parts of time and date
//  Implemented because I did not know how to use the structs generated by EW
/*****************************************************************************/
char clock_getMonth( void ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
    return sDate.Month;
}

char clock_getWeekDay( void ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
    return sDate.WeekDay;
}

char clock_getDate( void ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
    return sDate.Date;
}

char clock_getHour( void ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
    return sTime.Hours;
}

char clock_getMinute( void )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
    return sTime.Minutes;
}

char clock_getSecond( void )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    return sTime.Seconds;
}


void clock_setMonth( char month )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    sDate.Month = month;
    HAL_RTC_SetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
}

void clock_setWeekDay( char weekDay )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    sDate.WeekDay = weekDay;
    HAL_RTC_SetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
}

void clock_setDate( char date )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    sDate.Date = date;
    HAL_RTC_SetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);
}

void clock_setHour( char hour )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    sTime.Hours = hour;
    HAL_RTC_SetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
}

void clock_setMinute( char minute )
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    sTime.Minutes = minute;
    HAL_RTC_SetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
}

void clock_setSecond( char second ) 
{
    RTC_DateTypeDef sDate = {0};
    RTC_TimeTypeDef sTime = {0};

    HAL_RTC_GetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&RtcHandle, &sDate, RTC_FORMAT_BIN);

    sTime.Seconds = second;
    HAL_RTC_SetTime(&RtcHandle, &sTime, RTC_FORMAT_BIN);
}